@startuml
title "EchoBoat Data Distribution Overview"
skinparam componentStyle rectangle
' skinparam linetype ortho

component "Pixhawk 4" as PH
component "PC"
component "SBES"

together {
together {
    component "GNSS 1" as GNSS1
    component "GNSS Controller" as GNSSC
}
component "GNSS 2 PPSonly" as GNSS2
component "IMU"
component "LIDAR"
}

together {
component "Power Module STBD" as PMstbd
component "Power Module Bow" as PMbow
}

component "Electronic Speed Controller PS" as ESCps
component "Electronic Speed Controller STBD" as ESCstbd
component "RC Receiver" as RCtrans

package "Ground Control Station"{
    component "Remote Controller" as RC
    component "Laptop"
    component "Wifi-Antenna 1" as Wifi1
}
component "Wifi-Antenna 2" as Wifi2

RCtrans <-> PH
RC <..down..> RCtrans

Wifi1 <-left-> Laptop
Wifi1 <..> Wifi2
Wifi2 <-right-> PC

PMbow -> PH 
PMstbd -> PH

PH <-up-> PC

SBES -> PC

' IMU --> LIDAR
LIDAR -> PC
GNSS2 -l-> LIDAR
GNSS2 -u-> IMU

GNSS1 <.> GNSSC
GNSS1 --> IMU
IMU -> PH
IMU -> PC

PH -down-> ESCps
PH -down-> ESCstbd

' [Battery PS] -up-> ESCps
' [PMstbd] -right-> ESCstbd

' hide @unlinked
@enduml