@startuml
title "EchoBoat Systems Overview"
skinparam componentStyle rectangle

component "Pixhawk 4" as PH
component "PC"
component "SBES"
component "GNSS"
component "IMU"
component "Power Module STBD" as PMaft
component "Power Module Bow" as PMbow
component "Battery PS"
component "Battery STBD"
component "Battery bow"
component "Electronic Speed Controller PS" as ESCPS
component "Electronic Speed Controller STBD" as ESCSTBD
component "Motor PS"
component "Motor STBD"
component "RC Receiver" as RCtrans

component "Remote Controller" as RC
component "Laptop"
component "Wifi-Antenna 1" as Wifi1
component "Wifi-Antenna 2" as Wifi2

RCtrans <-right-> PH
RC <..> RCtrans

[Laptop] <-> Wifi1
Wifi1 <..> Wifi2
Wifi2 <-> PC

PH <-right- PMbow
PH <-down- PMaft
PMaft <- [Battery STBD]
PMbow <- [Battery bow]


PH <-up-> [PC]

[SBES] -left-> [PC]
[SBES] <-down- [Battery bow]
[PC] <-down- [Battery bow]

[PC] <-up- IMU

PH <-up- [GNSS]
[GNSS] -> [PC]

PH -down-> ESCPS
PH -down-> ESCSTBD

ESCPS <-down- [Battery PS]
ESCSTBD <-down- [Battery STBD]

[Motor PS] <-up- ESCPS
[Motor STBD] <-up- ESCSTBD

@enduml